### ISSUE TITLE
Question: How?

### ISSUE THREAD

**Issue by Minemetero** [lingbopro/soberjs-vscode#1]
开下Discussion供我说废话）

**Comment by Minemetero** [comment]
额为啥我看啥代码也没有啊这Github 没显示编程语言

**Comment by Minemetero** [comment]
你README.md还没加呢

**Comment by Minemetero** [comment]
![image_2024-07-01_134221293](https://github.com/lingbopro/soberjs-vscode/assets/156386015/38418911-dd42-4928-a09a-26afc2e6efb9)
你开什么国际玩笑呢（

**Comment by Minemetero** [comment]
你这个库的README.md的链接给错了

**Comment by Minemetero** [comment]
看起来很简单。。。。

**Comment by Minemetero** [comment]
让我试试

**Comment by lingbopro** [comment]
> ![image_2024-07-01_134221293](https://github.com/lingbopro/soberjs-vscode/assets/156386015/38418911-dd42-4928-a09a-26afc2e6efb9)
> 你开什么国际玩笑呢（

在Actions里忘创建out文件夹了，导致打包不出来，就失败力

**Comment by lingbopro** [comment]
> 额为啥我看啥代码也没有啊这Github 没显示编程语言

此扩展基于JSON :)

**Comment by lingbopro** [comment]
> 你这个库的README.md的链接给错了

em?

**Comment by lingbopro** [comment]
> 开下Discussion供我说废话）

我开discussions了

**Comment by Minemetero** [comment]
out/
out/**

nm :(

**Comment by Minemetero** [comment]
out file 被你吃了

**Comment by Minemetero** [comment]
不过打包成功了

**Comment by lingbopro** [comment]
> out file 被你吃了, 输出文件放哪啊

输出文件由Actions生成并发布，不存到repo文件里

**Comment by lingbopro** [comment]
另外我在Actions里忘了创建`out`文件夹了（

**Comment by Minemetero** [comment]
............................
吧代码给我我补上

**Comment by Minemetero** [comment]
我在不断地打补丁。。。。

**Comment by lingbopro** [comment]
我觉得吧

就循序渐进吧

**Comment by Minemetero** [comment]
啊？什么意思

**Comment by lingbopro** [comment]
> 啊？什么意思

就是说这个pr感觉改的有点多
感觉整的有点乱

**Comment by Minemetero** [comment]
> > 啊？什么意思
> 
> 就是说这个pr感觉改的有点多 感觉整的有点乱

我有主意了，你觉得改的太多那我们就多升几个版本号 :)
